### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by truongluan303** [Trident-Development/linkedin-job-post-discord-bot#5]
```
An exception has occurred while executing command `post-job`:
Traceback (most recent call last):
  File "/home/luan/Workspace/linkedin-job-post-discord-bot/.venv/lib/python3.10/site-packages/discord_slash/client.py", line 1353, in invoke_command
    await func.invoke(ctx, **args)
  File "/home/luan/Workspace/linkedin-job-post-discord-bot/.venv/lib/python3.10/site-packages/discord_slash/model.py", line 209, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "/home/luan/Workspace/linkedin-job-post-discord-bot/disc/cog.py", line 42, in _post_job
    await ctx.send(embed=embed_content)
  File "/home/luan/Workspace/linkedin-job-post-discord-bot/.venv/lib/python3.10/site-packages/discord_slash/context.py", line 256, in send
    await self._http.post_initial_response(json_data, self.interaction_id, self._token)
  File "/home/luan/Workspace/linkedin-job-post-discord-bot/.venv/lib/python3.10/site-packages/discord/http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 40060): Interaction has already been acknowledged.
```
Needs investigation.

**Comment by allen-tran** [comment]
May be an issue with more than 1 local instances running at the same time.
